train_file: ['/net/acadia10a/data/zkhan/downstream-finetuning-json/refcoco+_train.json']
test_file: [
  '/net/acadia10a/data/zkhan/downstream-finetuning-json/refcoco+_val.json',
  '/net/acadia10a/data/zkhan/downstream-finetuning-json/refcoco+_test.json'
]

refcoco_data: '/net/acadia10a/data/zkhan/refcoco+/'
det_file: '/net/acadia10a/data/zkhan/downstream-finetuning-json/refcoco+/dets.json'            
coco_file: '/net/acadia10a/data/zkhan/downstream-finetuning-json/refcoco+/cocos.json'    

image_root: '/net/acadia10a/data/zkhan/coco2014'

bert_config: 'configs/shared_bert.json'

image_res: 384
batch_size: 32

queue_size: 65536
momentum: 0.995
vision_width: 768
embed_dim: 256
temp: 0.07

alpha: 0.4
distill: True
warm_up: True
mlm_probability: 0.15

optimizer: {opt: adamW, lr: 1e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-5, epochs: 5, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}

vit_mask_token: false