cache: '/net/acadia4a/data/zkhan/simla_cache'

bert_config: 'configs/shared_bert.json'

image_res: 384
batch_size_train: 32
batch_size_test: 64

vision_width: 768
embed_dim: 256
temp: 0.07
k_test: 128

# Not needed during inference, but model throws error if
# these keys aren't there.
mlm_probability: 0.00
queue_size: 65536
momentum: 0

vit_mask_token: false