train_file: ['/net/acadia10a/data/zkhan/downstream-finetuning-json/vqa_train.json',
             '/net/acadia10a/data/zkhan/downstream-finetuning-json/vqa_val.json',   
             '/net/acadia10a/data/zkhan/downstream-finetuning-json/vg_qa_fixed.json']
             
test_file: ['/net/acadia10a/data/zkhan/downstream-finetuning-json/vqa_test.json']
answer_list: '/net/acadia10a/data/zkhan/downstream-finetuning-json/answer_list.json'

vqa_root: '/net/acadia10a/data/zkhan/coco2014/' #train2014/
vg_root: '/net/acadia10a/data/zkhan/visual-genome-sandbox'  #image/

image_res: 384
batch_size_train: 32 
batch_size_test: 16 
k_test: 128

alpha: 0.4
distill: True
warm_up: True

eos: '[SEP]'

bert_config: 'configs/shared_bert.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 8, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}


vit_mask_token: false